CREATE TABLE USERS(ID VARCHAR(100),FIRST_NAME VARCHAR(100),LAST_NAME VARCHAR(100),EMAIL_ID VARCHAR(100),MOBILE_NUMBER LONG);
CREATE TABLE LOCATIONS (ID VARCHAR(100),LOCATION VARCHAR(100),LAST_UPDATED timestamp);
CREATE TABLE FRIENDS (ID VARCHAR(100),friend_id VARCHAR(100),LAST_UPDATED timestamp,CREATED_ON timestamp);