CREATE TABLE USERS(ID VARCHAR(100),FIRST_NAME VARCHAR(100),LAST_NAME VARCHAR(100),EMAIL_ID VARCHAR(100),MOBILE_NUMBER LONG);
CREATE TABLE LOCATIONS (ID LONG,LOCATION VARCHAR(100),LAST_UPDATED timestamp);
CREATE TABLE FRIENDS (GENERATED_ID int PRIMARY KEY AUTO_INCREMENT,ID LONG,FRIEND_ID LONG,STATUS VARCHAR(100),LAST_UPDATED timestamp,CREATED_ON timestamp);
CREATE TABLE DEVICES (ID VARCHAR(250) PRIMARY KEY, USER_ID LONG);